/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'Fira Code', 'monospace'],
        display: ['Inter', 'system-ui', 'sans-serif'],
      },
      colors: {
        bg:        '#080808',
        surface:   '#0f0f0f',
        'surface-2': '#141414',
        'surface-3': '#1a1a1a',
        border:    '#1e1e1e',
        'border-2': '#2a2a2a',
        muted:     '#404040',
        subtle:    '#666666',
        secondary: '#999999',
        text:      '#e2e2e2',
        heading:   '#f0f0f0',
        white:     '#ffffff',
        accent:    '#00d4aa',
        'accent-2': '#00b894',
        'accent-glow': 'rgba(0,212,170,0.15)',
        'accent-subtle': 'rgba(0,212,170,0.08)',
        amber:     '#f59e0b',
        'amber-subtle': 'rgba(245,158,11,0.08)',
      },
      fontSize: {
        '2xs': ['0.65rem', { lineHeight: '1rem' }],
      },
      letterSpacing: {
        tightest: '-0.05em',
        tighter:  '-0.03em',
        tight:    '-0.02em',
        snug:     '-0.01em',
      },
      boxShadow: {
        'glow-sm': '0 0 20px rgba(0,212,170,0.08)',
        'glow':    '0 0 40px rgba(0,212,170,0.12)',
        'glow-lg': '0 0 80px rgba(0,212,170,0.15)',
        'card':    '0 1px 3px rgba(0,0,0,0.4), 0 1px 2px rgba(0,0,0,0.6)',
        'card-hover': '0 4px 24px rgba(0,0,0,0.5)',
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'grid-pattern': `linear-gradient(rgba(255,255,255,0.02) 1px, transparent 1px),
                         linear-gradient(90deg, rgba(255,255,255,0.02) 1px, transparent 1px)`,
      },
      backgroundSize: {
        'grid': '40px 40px',
      },
      animation: {
        'fade-up':    'fadeUp 0.7s cubic-bezier(0.22,1,0.36,1) forwards',
        'fade-in':    'fadeIn 0.5s ease forwards',
        'blink':      'blink 1s step-end infinite',
        'pulse-slow': 'pulse 3s cubic-bezier(0.4,0,0.6,1) infinite',
        'slide-right':'slideRight 0.5s cubic-bezier(0.22,1,0.36,1) forwards',
        'float':      'float 6s ease-in-out infinite',
        'scan':       'scan 3s linear infinite',
      },
      keyframes: {
        fadeUp:     { from: { opacity:'0', transform:'translateY(28px)' }, to: { opacity:'1', transform:'translateY(0)' } },
        fadeIn:     { from: { opacity:'0' }, to: { opacity:'1' } },
        blink:      { '0%,100%': { opacity:'1' }, '50%': { opacity:'0' } },
        slideRight: { from: { opacity:'0', transform:'translateX(-16px)' }, to: { opacity:'1', transform:'translateX(0)' } },
        float:      { '0%,100%': { transform:'translateY(0)' }, '50%': { transform:'translateY(-8px)' } },
        scan:       { '0%': { transform:'translateY(-100%)' }, '100%': { transform:'translateY(400%)' } },
      },
    },
  },
  plugins: [],
};
